language: bash

sudo: required

branches:
  only:
    - master
    - beta
    - develop

before_script:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
  - sudo apt-get update -qq
  - sudo apt-get install -qq wget python2.7
  - wget https://raw.githubusercontent.com/Schrolli91/BOSWatch/${TRAVIS_BRANCH}/install.sh
  - chmod +x install.sh
  - cat /etc/os-release
  - echo ${TRAVIS_BRANCH}
  - sudo ./install.sh -b ${TRAVIS_BRANCH}

env:
  - module=base
  - module=mysql
  - module=httpRequest

script:
  - sudo /bin/bash citest/test.sh
